version: 1
formatters:
  default_console_process:
    format: '%(asctime)s %(processName)s %(levelname)s %(funcName)s %(message)s'
    datefmt: '%d-%m-%y %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default_console_process
    stream: ext://sys.stdout
  colored_console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default_console_process
    stream: ext://sys.stdout
loggers:
  custom:
    level: DEBUG
    handlers: [console]
    propagate: no
  colored:
    level: DEBUG
    handlers: [colored_console]
    propagate: no
root:
  level: INFO
  handlers: [colored_console]
